config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :comments

  devise_for :users
  resources :links do
	  member do
		  put "like", to: "links#upvote"
		  put "dislike", to: "links#downvote"
	  end
	  resources :comments

  end

   root 'links#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

    def initialize(user)
      user ||= User.new
    
      if user.admin?
        can :manage, :all
    
      else
      
        can :update, Link do |link|
          link.user == user
        end
        
        can :destroy, Link do |link|
          link.user == user
        end
      
        can :destroy, Comment do |comment|
          comment.user == user
        end
      
        can :create, Link
        can :create, Comment
#	else
        can :read, :all
    
      end
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
	
	acts_as_votable
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/subsite.rb
class Subsite < ActiveRecord::Base
  extend FriendlyId
	friendly_id :name, use: :slugged
  
  has_many :links, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :links, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	
	before_filter :configure_permitted_parameters, if: :devise_controller?
	
	protected
	
	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) << :name
		devise_parameter_sanitizer.for(:account_update) << :name
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @comments = Comment.all
  end

  def show
    respond_with(@comment)
	authorize! :read, @comment
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
  @link = Link.friendly.find(params[:link_id])
  @comment = @link.comments.new(comment_params)
  @comment.user = current_user
 
  respond_to do |format|
    if @comment.save
      format.html { redirect_to @link, notice: 'Comment was successfully created.' }
      format.json { render json: @comment, status: :created, location: @comment }
    else
      format.html { render action: "new" }
      format.json { render json: @comment.errors, status: :unprocessable_entity }
    end
  end
end
 

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
	redirect_to :back
  end

def upvote
  @comment = Comment.find(params[:id])
  @comment.upvote_by current_user
  redirect_to :back
end
 
def downvote
  @comment = Comment.find(params[:id])
  @comment.downvote_by current_user
  redirect_to :back
end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authorized_user, only: [:edit, :update, :destroy]
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all.order(:cached_votes_score => :desc)
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
    
  end

	def authorized_user
  @link = current_user.links.find_by_slug(params[:id])
  redirect_to links_path, notice: "Not authorized to edit this link" if @link.nil?
end
	
def upvote
  @link = Link.friendly.find(params[:id])
  @link.upvote_by current_user
  redirect_to :back
end
 
def downvote
  @link = Link.friendly.find(params[:id])
  @link.downvote_by current_user
  redirect_to :back
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url, :user_id)
    end
end

app/controllers/subsites_controller.rb
class SubsitesController < ApplicationController
  before_action :set_subsite, only: [:show, :edit, :update, :destroy]

  # GET /subsites
  # GET /subsites.json
  def index
    @subsites = Subsite.all
  end

  # GET /subsites/1
  # GET /subsites/1.json
  def show
  end

  # GET /subsites/new
  def new
    @subsite = Subsite.new
  end

  # GET /subsites/1/edit
  def edit
  end

  # POST /subsites
  # POST /subsites.json
  def create
    @subsite = Subsite.new(subsite_params)

    respond_to do |format|
      if @subsite.save
        format.html { redirect_to @subsite, notice: 'Subsite was successfully created.' }
        format.json { render :show, status: :created, location: @subsite }
      else
        format.html { render :new }
        format.json { render json: @subsite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subsites/1
  # PATCH/PUT /subsites/1.json
  def update
    respond_to do |format|
      if @subsite.update(subsite_params)
        format.html { redirect_to @subsite, notice: 'Subsite was successfully updated.' }
        format.json { render :show, status: :ok, location: @subsite }
      else
        format.html { render :edit }
        format.json { render json: @subsite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subsites/1
  # DELETE /subsites/1.json
  def destroy
    @subsite.destroy
    respond_to do |format|
      format.html { redirect_to subsites_url, notice: 'Subsite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subsite
      @subsite = Subsite.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subsite_params
      params.require(:subsite).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/subsites_helper.rb
module SubsitesHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
<div class='col-xs-2'></div>
<div class='col-xs-10'>
	<div class='comments_wrapper clearfix'>
		<div class='pull-left'>
			<h4><%= comment.body %></h4>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %></strong> by <%= comment.user.name %></small></p>
		</div>
		
		<div class='btn-group pull-right'>
			<% if can? :destroy, comment %>
				<%= link_to "Delete", comment, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
			<% end %>
		</div>
	</div>
</div>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :link_id %>
    <%= f.input :body %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
		<p class='navbar-brand'><%= link_to "Ureadit", root_path %></p>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<% if user_signed_in? %>
      	<ul class="nav navbar-nav">
    	<li><%= link_to 'Submit link', new_link_path %></li>
		<% end %>       
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
		    <% if user_signed_in? %>
          <li></li>
        	<li><%= link_to 'Account', edit_user_registration_path %></li>
   			  <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
		    <% else %>
    		  <li><%= link_to 'Sign up', new_user_registration_path %></li>
    		  <li><%= link_to 'Log in', new_user_session_path %></li>
		    <% end %>
  	  </ul>

        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ureadit "Reddit clone"</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
<h2 class="text-center">Edit Link</h2>
<%= simple_form_for(@link, html: {class: "form-signin"}) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.input :title, required: false, autofocus: true, label: false, placeholder: "Title", input_html: {class: "form-control"} %>
    <%= f.input :url, required: false, autofocus: true, label: false, placeholder: "URL", input_html: {class: "form-control"} %>
    <%= f.submit "Submit", class: "btn btn-block btn-primary" %>


<% end %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>


<% @links.each do |link| %>

<div class='col-xs-1'>
	<br><br>
<div class='text-right'><%= link_to like_link_path(link), method: :put, class: "btn btn-success btn-xs" do %>
    <i class="fa fa-chevron-up"></i>
  <% end %><br>
	<%= link.get_upvotes.size - link.get_downvotes.size %>       <br>
  <%= link_to dislike_link_path(link), method: :put, class: "btn btn-danger btn-xs" do %>
    <i class="fa fa-chevron-down"></i>	
		<% end %></div>
</div>
<div class='col-xs-11'>
<h3><%= link_to link.title, link %><br>
	<h6 class="author">Submitted <%= time_ago_in_words(link.created_at) %> by <%= link.user.name %></h6>
	<div class="button">
	<%= link_to "Visit Link", link.url, class: "btn btn-primary btn-sm" %>
	<%= link_to pluralize(link.comments.count, 'Comment'), link, class: "btn btn-primary btn-sm" %>
	<% if link.user == current_user %>
	<%= link_to "Edit", edit_link_path(link), class: "btn btn-warning btn-sm" %>
	<%= link_to "Delete", link, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
    <% end %>
	</div>

</h3>
	</div>
<% end %>

app/views/links/new.html.erb
<h2 class="text-center">New Link</h2>
<%= simple_form_for(@link, html: {class: "form-signin"}) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.input :title, required: false, autofocus: true, label: false, placeholder: "Title", input_html: {class: "form-control"} %>
    <%= f.input :url, required: false, autofocus: true, label: false, placeholder: "URL", input_html: {class: "form-control"} %>
    <%= f.submit "Submit", class: "btn btn-block btn-primary" %>


<% end %>

app/views/links/show.html.erb
<div class='container'>
<div class='col-xs-1'>
	<br><br>
<div class='text-right'><%= link_to like_link_path(@link), method: :put, class: "btn btn-success btn-xs" do %>
    <i class="fa fa-chevron-up"></i>
  <% end %><br>
	<%= @link.get_upvotes.size - @link.get_downvotes.size %>       <br>
  <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-danger btn-xs" do %>
    <i class="fa fa-chevron-down"></i>	
		<% end %></div>
</div>
<div class='col-xs-11'>
<h3><%= link_to @link.title, @link %><br>
	<h6 class="author">Submitted by <%= @link.user.name %></h6>
	<div class="button">
	<%= link_to "Visit Link", @link.url, class: "btn btn-primary btn-sm" %>
	
	<% if @link.user == current_user %>
	<%= link_to "Edit", edit_link_path(@link), class: "btn btn-warning btn-sm" %>
	<%= link_to "Delete", @link, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
	<% end %>
	</div>
</h3>
</div>

<br><br><br><br><br><br>

	<h3 class='comments_title'>
	<%= @link.comments.count %> Comments
</h3>


<div id='comments'>
	<%= render :partial => @link.comments.order(:cached_votes_score => :desc) %>
</div>

<% if user_signed_in? %>
<%= simple_form_for [@link, Comment.new] do |f| %>
	<div class='col-xs-2'>
	</div>
	<div class='col-xs-10'>
	<div class='field'>
		<%= f.text_area :body, class: "form-control" %>
	</div>
	<br>
	<%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>
	<% else %>
	<div class='text-center'><strong>To comment, please login!</strong></div>
<% end %>
	</div>
	</div>

app/views/subsites/_form.html.erb
<%= simple_form_for(@subsite) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subsites/edit.html.erb
<h1>Editing Subsite</h1>

<%= render 'form' %>

<%= link_to 'Show', @subsite %> |
<%= link_to 'Back', subsites_path %>

app/views/subsites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subsites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subsites.each do |subsite| %>
      <tr>
        <td><%= subsite.name %></td>
        <td><%= subsite.description %></td>
        <td><%= link_to 'Show', subsite %></td>
        <td><%= link_to 'Edit', edit_subsite_path(subsite) %></td>
        <td><%= link_to 'Destroy', subsite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subsite', new_subsite_path %>

app/views/subsites/new.html.erb
<h2 class='text-center'>New Subsite</h2>
<%= simple_form_for(@subsite, html: {class: "form-signin"}) do |f| %>

    <%= f.input :name, required: true, autofocus: true, label: false, placeholder: "Name", input_html: {class: "form-control"} %>
    <%= f.input :description, required: true, autofocus: true, label: false, placeholder: "Description", input_html: {class: "form-control"} %>
    <%= f.submit "Submit", class: "btn btn-block btn-primary" %>


<% end %>

app/views/subsites/show.html.erb
<h2 class='text-center'><%= @subsite.name %></h2>

<p id="notice"><%= notice %></p>

<div class='col-sm-10'>
<% links.each do |link| %>

<div class='col-xs-1'>
	<br><br>
<div class='text-right'><%= link_to like_link_path(link), method: :put, class: "btn btn-success btn-xs" do %>
    <i class="fa fa-chevron-up"></i>
  <% end %><br>
	<%= link.get_upvotes.size - link.get_downvotes.size %>       <br>
  <%= link_to dislike_link_path(link), method: :put, class: "btn btn-danger btn-xs" do %>
    <i class="fa fa-chevron-down"></i>	
		<% end %></div>
</div>
<div class='col-xs-11'>
<h3><%= link_to link.title, link %><br>
	<h6 class="author">Submitted <%= time_ago_in_words(link.created_at) %> by <%= link.user.name %></h6>
	<div class="button">
	<%= link_to "Visit Link", link.url, class: "btn btn-primary btn-sm" %>
	<%= link_to pluralize(link.comments.count, 'Comment'), link, class: "btn btn-primary btn-sm" %>
	<% if link.user == current_user %>
	<%= link_to "Edit", edit_link_path(link), class: "btn btn-warning btn-sm" %>
	<%= link_to "Delete", link, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
    <% end %>
	</div>
</h3>
</div>

<% end %>
</div>
<div class='col-sm-2'>
  <%= link_to 'Submit New Link', new_link_path, class: "btn btn-info btn-block" %>
  <br>
  <%= link_to 'Create New Subsite', new_subsite_path, class: "btn btn-info btn-block" %>
</div>